/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bigotes_colas.views;

import javax.swing.JOptionPane;

/**
 *
 * @author gbcya
 */
public class Citas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Citas.class.getName());

    /**
     * Creates new form Citas
     */
    public Citas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEncabezado = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        lblSubtituloPantalla = new javax.swing.JLabel();
        lblUsuarioSesion = new javax.swing.JLabel();
        pnlSidebar = new javax.swing.JPanel();
        btnNavClientes = new javax.swing.JButton();
        btnNavMascotas = new javax.swing.JButton();
        btnNavHistorial = new javax.swing.JButton();
        btnNavCitas = new javax.swing.JButton();
        btnNavInventario = new javax.swing.JButton();
        btnNavReportes = new javax.swing.JButton();
        btnNavUsuarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        pnlFormularioCita = new javax.swing.JPanel();
        lblCitaNueva = new javax.swing.JLabel();
        comboMascotaCita = new javax.swing.JComboBox<>();
        comboVeterinario = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        lblNota = new javax.swing.JLabel();
        btnAgendarCita = new javax.swing.JButton();
        lblMascota = new javax.swing.JLabel();
        lblVeterinario = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblMotivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEncabezado.setBackground(new java.awt.Color(27, 59, 59));
        pnlEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        lblMarca.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Bigotes & Colas");

        lblSubtituloPantalla.setForeground(new java.awt.Color(207, 227, 223));
        lblSubtituloPantalla.setText(" | Citas");

        lblUsuarioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioSesion.setText("Sesion: Administrador");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMarca)
                .addGap(60, 60, 60)
                .addComponent(lblSubtituloPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(lblUsuarioSesion)
                .addGap(33, 33, 33))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(lblSubtituloPantalla)
                    .addComponent(lblUsuarioSesion))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlSidebar.setBackground(new java.awt.Color(233, 243, 241));

        btnNavClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnNavClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavClientes.setForeground(new java.awt.Color(74, 74, 74));
        btnNavClientes.setText("Clientes");

        btnNavMascotas.setBackground(new java.awt.Color(233, 243, 241));
        btnNavMascotas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavMascotas.setForeground(new java.awt.Color(74, 74, 74));
        btnNavMascotas.setText("Mascotas");
        btnNavMascotas.addActionListener(this::btnNavMascotasActionPerformed);

        btnNavHistorial.setBackground(new java.awt.Color(233, 243, 241));
        btnNavHistorial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavHistorial.setForeground(new java.awt.Color(74, 74, 74));
        btnNavHistorial.setText("Historial");
        btnNavHistorial.addActionListener(this::btnNavHistorialActionPerformed);

        btnNavCitas.setBackground(new java.awt.Color(46, 125, 107));
        btnNavCitas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavCitas.setForeground(new java.awt.Color(255, 255, 255));
        btnNavCitas.setText("Citas");
        btnNavCitas.addActionListener(this::btnNavCitasActionPerformed);

        btnNavInventario.setBackground(new java.awt.Color(233, 243, 241));
        btnNavInventario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavInventario.setForeground(new java.awt.Color(74, 74, 74));
        btnNavInventario.setText("Inventario");
        btnNavInventario.addActionListener(this::btnNavInventarioActionPerformed);

        btnNavReportes.setBackground(new java.awt.Color(233, 243, 241));
        btnNavReportes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavReportes.setForeground(new java.awt.Color(74, 74, 74));
        btnNavReportes.setText("Reportes");

        btnNavUsuarios.setBackground(new java.awt.Color(233, 243, 241));
        btnNavUsuarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavUsuarios.setForeground(new java.awt.Color(74, 74, 74));
        btnNavUsuarios.setText("Usuarios");
        btnNavUsuarios.addActionListener(this::btnNavUsuariosActionPerformed);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNavClientes)
                    .addComponent(btnNavMascotas)
                    .addComponent(btnNavHistorial)
                    .addComponent(btnNavCitas)
                    .addComponent(btnNavInventario)
                    .addComponent(btnNavReportes)
                    .addComponent(btnNavUsuarios))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnNavClientes)
                .addGap(18, 18, 18)
                .addComponent(btnNavMascotas)
                .addGap(18, 18, 18)
                .addComponent(btnNavHistorial)
                .addGap(18, 18, 18)
                .addComponent(btnNavCitas)
                .addGap(18, 18, 18)
                .addComponent(btnNavInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavReportes)
                .addGap(18, 18, 18)
                .addComponent(btnNavUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:00", "Firulais", "Maria Lopez", "Dr. Mendez", "Vacuna anual"},
                {"09:30", "Michi", "Carlos Ruiz", "Dra. Solis", "Consulta general"},
                {"10:00", "Rocky", "Ana Gomez", "Dr. Mendez", "Desparasitacion"},
                {"11:30", "Luna", "Maria Lopez", "Dra. Solis", "Control de peso"},
                {null, null, null, null, null}
            },
            new String [] {
                "Hora", "Mascota", "Dueño", "Veterinario", "Motivo"
            }
        ));
        jScrollPane1.setViewportView(tablaCitas);

        pnlFormularioCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 243, 241), 2));

        lblCitaNueva.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCitaNueva.setText("Nueva cita");

        comboMascotaCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Firulais", "Michi", "Rocky", "Luna" }));

        comboVeterinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Mendez", "Dra. Solis", " " }));

        txtFecha.setText("dd/mm/aaaa");

        txtHora.setText("hh:mm");

        lblNota.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblNota.setForeground(new java.awt.Color(74, 74, 74));
        lblNota.setText("Se validara que no exista cruce de horario con el mismo veterinario.");

        btnAgendarCita.setBackground(new java.awt.Color(46, 125, 107));
        btnAgendarCita.setText("Agendar cita");
        btnAgendarCita.addActionListener(this::btnAgendarCitaActionPerformed);

        lblMascota.setText("Mascota");

        lblVeterinario.setText("Veterinario");

        lblFecha.setText("Fecha");

        lblHora.setText("Hora");

        lblMotivo.setText("Motivo");

        javax.swing.GroupLayout pnlFormularioCitaLayout = new javax.swing.GroupLayout(pnlFormularioCita);
        pnlFormularioCita.setLayout(pnlFormularioCitaLayout);
        pnlFormularioCitaLayout.setHorizontalGroup(
            pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNota)
                .addGap(39, 39, 39))
            .addGroup(pnlFormularioCitaLayout.createSequentialGroup()
                .addGroup(pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioCitaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMascota)
                            .addComponent(lblVeterinario)
                            .addComponent(lblFecha)
                            .addComponent(lblHora)
                            .addComponent(lblMotivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMascotaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFormularioCitaLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnAgendarCita))
                    .addGroup(pnlFormularioCitaLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblCitaNueva)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        pnlFormularioCitaLayout.setVerticalGroup(
            pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioCitaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblCitaNueva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFormularioCitaLayout.createSequentialGroup()
                        .addGroup(pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboMascotaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMascota))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVeterinario))
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHora))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMotivo))
                .addGap(18, 18, 18)
                .addComponent(lblNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgendarCita)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlFormularioCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlFormularioCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(819, 819, 819))
                        .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavMascotasActionPerformed
        // TODO add your handling code here:
        new Mascotas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavMascotasActionPerformed

    private void btnNavHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavHistorialActionPerformed
        // TODO add your handling code here:
        new Historial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavHistorialActionPerformed

    private void btnNavCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavCitasActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnNavCitasActionPerformed

    private void btnNavInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavInventarioActionPerformed
        // TODO add your handling code here:
        new Inventario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavInventarioActionPerformed

    private void btnNavUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavUsuariosActionPerformed
        // TODO add your handling code here:
        new Usuarios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavUsuariosActionPerformed

    private void btnAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarCitaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Accion de prototipo: \"Agendar cita\"\n(sin logica de negocio todavia)", "Prototipo no funcional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAgendarCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Citas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarCita;
    private javax.swing.JButton btnNavCitas;
    private javax.swing.JButton btnNavClientes;
    private javax.swing.JButton btnNavHistorial;
    private javax.swing.JButton btnNavInventario;
    private javax.swing.JButton btnNavMascotas;
    private javax.swing.JButton btnNavReportes;
    private javax.swing.JButton btnNavUsuarios;
    private javax.swing.JComboBox<String> comboMascotaCita;
    private javax.swing.JComboBox<String> comboVeterinario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCitaNueva;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMascota;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblSubtituloPantalla;
    private javax.swing.JLabel lblUsuarioSesion;
    private javax.swing.JLabel lblVeterinario;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlFormularioCita;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JTable tablaCitas;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
