/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bigotes_colas.views;

import javax.swing.JOptionPane;

/**
 *
 * @author gbcya
 */
public class Clientes extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Clientes.class.getName());

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuMascotas = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuCitas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        pnlEncabezado = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        lblSubtituloPantalla = new javax.swing.JLabel();
        lblUsuarioSesion = new javax.swing.JLabel();
        pnlSidebar = new javax.swing.JPanel();
        btnNavClientes = new javax.swing.JButton();
        btnNavMascotas = new javax.swing.JButton();
        btnNavHistorial = new javax.swing.JButton();
        btnNavCitas = new javax.swing.JButton();
        btnNavInventario = new javax.swing.JButton();
        btnNavReportes = new javax.swing.JButton();
        btnNavUsuarios = new javax.swing.JButton();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnAgregarCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnVerMascotas = new javax.swing.JButton();

        menuArchivo.setText("Archivo");

        itemSalir.setText("Salir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        menuArchivo.add(itemSalir);

        jMenuBar1.add(menuArchivo);

        menuClientes.setText("Clientes");

        jMenuItem1.setText("prototipo - sin logica");
        jMenuItem1.setEnabled(false);
        menuClientes.add(jMenuItem1);

        jMenuBar1.add(menuClientes);

        menuMascotas.setText("Mascotas");

        jMenuItem2.setText(" (prototipo - sin logica)");
        jMenuItem2.setEnabled(false);
        menuMascotas.add(jMenuItem2);

        jMenuBar1.add(menuMascotas);

        menuCitas.setText("Citas");

        jMenuItem3.setText(" (prototipo - sin logica)");
        jMenuItem3.setEnabled(false);
        menuCitas.add(jMenuItem3);

        jMenuBar1.add(menuCitas);

        menuInventario.setText("Inventario");

        jMenuItem4.setText("(prototipo - sin logica)");
        jMenuItem4.setEnabled(false);
        menuInventario.add(jMenuItem4);

        jMenuBar1.add(menuInventario);

        menuReportes.setText("Reportes");

        jMenuItem5.setText(" (prototipo - sin logica)");
        jMenuItem5.setEnabled(false);
        menuReportes.add(jMenuItem5);

        jMenuBar1.add(menuReportes);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEncabezado.setBackground(new java.awt.Color(27, 59, 59));
        pnlEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        lblMarca.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Bigotes & Colas");

        lblSubtituloPantalla.setForeground(new java.awt.Color(207, 227, 223));
        lblSubtituloPantalla.setText(" | Clientes ");

        lblUsuarioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioSesion.setText("Sesion: Administrador");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMarca)
                .addGap(60, 60, 60)
                .addComponent(lblSubtituloPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(lblUsuarioSesion)
                .addGap(33, 33, 33))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(lblSubtituloPantalla)
                    .addComponent(lblUsuarioSesion))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlSidebar.setBackground(new java.awt.Color(233, 243, 241));

        btnNavClientes.setBackground(new java.awt.Color(46, 125, 107));
        btnNavClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnNavClientes.setText("Clientes");

        btnNavMascotas.setBackground(new java.awt.Color(233, 243, 241));
        btnNavMascotas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavMascotas.setForeground(new java.awt.Color(74, 74, 74));
        btnNavMascotas.setText("Mascotas");
        btnNavMascotas.addActionListener(this::btnNavMascotasActionPerformed);

        btnNavHistorial.setBackground(new java.awt.Color(233, 243, 241));
        btnNavHistorial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavHistorial.setForeground(new java.awt.Color(74, 74, 74));
        btnNavHistorial.setText("Historial");
        btnNavHistorial.addActionListener(this::btnNavHistorialActionPerformed);

        btnNavCitas.setBackground(new java.awt.Color(233, 243, 241));
        btnNavCitas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavCitas.setForeground(new java.awt.Color(74, 74, 74));
        btnNavCitas.setText("Citas");
        btnNavCitas.addActionListener(this::btnNavCitasActionPerformed);

        btnNavInventario.setBackground(new java.awt.Color(233, 243, 241));
        btnNavInventario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavInventario.setForeground(new java.awt.Color(74, 74, 74));
        btnNavInventario.setText("Inventario");
        btnNavInventario.addActionListener(this::btnNavInventarioActionPerformed);

        btnNavReportes.setBackground(new java.awt.Color(233, 243, 241));
        btnNavReportes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavReportes.setForeground(new java.awt.Color(74, 74, 74));
        btnNavReportes.setText("Reportes");

        btnNavUsuarios.setBackground(new java.awt.Color(233, 243, 241));
        btnNavUsuarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavUsuarios.setForeground(new java.awt.Color(74, 74, 74));
        btnNavUsuarios.setText("Usuarios");
        btnNavUsuarios.addActionListener(this::btnNavUsuariosActionPerformed);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNavClientes)
                    .addComponent(btnNavMascotas)
                    .addComponent(btnNavHistorial)
                    .addComponent(btnNavCitas)
                    .addComponent(btnNavInventario)
                    .addComponent(btnNavReportes)
                    .addComponent(btnNavUsuarios))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnNavClientes)
                .addGap(18, 18, 18)
                .addComponent(btnNavMascotas)
                .addGap(18, 18, 18)
                .addComponent(btnNavHistorial)
                .addGap(18, 18, 18)
                .addComponent(btnNavCitas)
                .addGap(18, 18, 18)
                .addComponent(btnNavInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavReportes)
                .addGap(18, 18, 18)
                .addComponent(btnNavUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtBuscarCliente.setToolTipText("Buscar por nombre o telefono...");

        btnBuscarCliente.setText("Buscar");

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"C-001", "Maria Lopez", "5511-2233", "Zona 10 Ciudad", null},
                {"C-002", "Carlos Ruiz", "4422-9981", "Zona 7 Ciudad", null},
                {"C-003", "Ana Gomez", "3399-4410", "Zona 3 Ciudad", null},
                {"C-004", " Luis Perez", "5588-0021", " Zona 12 Ciudad", null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Telefono", "Direccion", "Mascotas "
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        btnAgregarCliente.setBackground(new java.awt.Color(46, 125, 107));
        btnAgregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente.setText("Agregar cliente");
        btnAgregarCliente.addActionListener(this::btnAgregarClienteActionPerformed);

        btnEditarCliente.setBackground(new java.awt.Color(46, 125, 107));
        btnEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(this::btnEditarClienteActionPerformed);

        btnEliminarCliente.setBackground(new java.awt.Color(46, 125, 107));
        btnEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(this::btnEliminarClienteActionPerformed);

        btnVerMascotas.setBackground(new java.awt.Color(46, 125, 107));
        btnVerMascotas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerMascotas.setText("Ver mascotas");
        btnVerMascotas.addActionListener(this::btnVerMascotasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnBuscarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerMascotas))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCliente)
                    .addComponent(btnEditarCliente)
                    .addComponent(btnEliminarCliente)
                    .addComponent(btnVerMascotas))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void btnNavMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavMascotasActionPerformed
        // TODO add your handling code here:
        new Mascotas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavMascotasActionPerformed

    private void btnNavHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavHistorialActionPerformed
        // TODO add your handling code here:
        new Historial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavHistorialActionPerformed

    private void btnNavCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavCitasActionPerformed
        // TODO add your handling code here:
        new Citas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavCitasActionPerformed

    private void btnNavInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavInventarioActionPerformed
        // TODO add your handling code here:
        new Inventario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavInventarioActionPerformed

    private void btnNavUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavUsuariosActionPerformed
        // TODO add your handling code here:
        new Usuarios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavUsuariosActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Accion de prototipo: \"Agregar cliente\"\n(sin logica de negocio todavia)", "Prototipo no funcional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Accion de prototipo: \"Eliminar cliente\"\n(sin logica de negocio todavia)", "Prototipo no funcional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Accion de prototipo: \"Eliminar cliente\"\n(sin logica de negocio todavia)", "Prototipo no funcional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnVerMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMascotasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Accion de prototipo: \"Ver mascotas cliente\"\n(sin logica de negocio todavia)", "Prototipo no funcional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerMascotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Clientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnNavCitas;
    private javax.swing.JButton btnNavClientes;
    private javax.swing.JButton btnNavHistorial;
    private javax.swing.JButton btnNavInventario;
    private javax.swing.JButton btnNavMascotas;
    private javax.swing.JButton btnNavReportes;
    private javax.swing.JButton btnNavUsuarios;
    private javax.swing.JButton btnVerMascotas;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblSubtituloPantalla;
    private javax.swing.JLabel lblUsuarioSesion;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuCitas;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenu menuMascotas;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtBuscarCliente;
    // End of variables declaration//GEN-END:variables
}
