/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bigotes_colas.views;

/**
 *
 * @author gbcya
 */
public class Inventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inventario.class.getName());

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        btnNavClientes = new javax.swing.JButton();
        btnNavMascotas = new javax.swing.JButton();
        btnNavHistorial = new javax.swing.JButton();
        btnNavCitas = new javax.swing.JButton();
        btnNavInventario = new javax.swing.JButton();
        btnNavReportes = new javax.swing.JButton();
        btnNavUsuarios = new javax.swing.JButton();
        pnlEncabezado = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        lblSubtituloPantalla = new javax.swing.JLabel();
        lblUsuarioSesion = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        lblAlertaStock = new javax.swing.JLabel();
        btnRegistrarEntrada = new javax.swing.JButton();
        btnRegistrarSalida = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSidebar.setBackground(new java.awt.Color(233, 243, 241));

        btnNavClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnNavClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavClientes.setForeground(new java.awt.Color(74, 74, 74));
        btnNavClientes.setText("Clientes");

        btnNavMascotas.setBackground(new java.awt.Color(233, 243, 241));
        btnNavMascotas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavMascotas.setForeground(new java.awt.Color(74, 74, 74));
        btnNavMascotas.setText("Mascotas");
        btnNavMascotas.addActionListener(this::btnNavMascotasActionPerformed);

        btnNavHistorial.setBackground(new java.awt.Color(233, 243, 241));
        btnNavHistorial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavHistorial.setForeground(new java.awt.Color(74, 74, 74));
        btnNavHistorial.setText("Historial");
        btnNavHistorial.addActionListener(this::btnNavHistorialActionPerformed);

        btnNavCitas.setBackground(new java.awt.Color(233, 243, 241));
        btnNavCitas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavCitas.setForeground(new java.awt.Color(74, 74, 74));
        btnNavCitas.setText("Citas");
        btnNavCitas.addActionListener(this::btnNavCitasActionPerformed);

        btnNavInventario.setBackground(new java.awt.Color(46, 125, 107));
        btnNavInventario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavInventario.setForeground(new java.awt.Color(74, 74, 74));
        btnNavInventario.setText("Inventario");
        btnNavInventario.addActionListener(this::btnNavInventarioActionPerformed);

        btnNavReportes.setBackground(new java.awt.Color(233, 243, 241));
        btnNavReportes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavReportes.setForeground(new java.awt.Color(74, 74, 74));
        btnNavReportes.setText("Reportes");

        btnNavUsuarios.setBackground(new java.awt.Color(233, 243, 241));
        btnNavUsuarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavUsuarios.setForeground(new java.awt.Color(74, 74, 74));
        btnNavUsuarios.setText("Usuarios");
        btnNavUsuarios.addActionListener(this::btnNavUsuariosActionPerformed);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNavClientes)
                    .addComponent(btnNavMascotas)
                    .addComponent(btnNavHistorial)
                    .addComponent(btnNavCitas)
                    .addComponent(btnNavInventario)
                    .addComponent(btnNavReportes)
                    .addComponent(btnNavUsuarios))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnNavClientes)
                .addGap(18, 18, 18)
                .addComponent(btnNavMascotas)
                .addGap(18, 18, 18)
                .addComponent(btnNavHistorial)
                .addGap(18, 18, 18)
                .addComponent(btnNavCitas)
                .addGap(18, 18, 18)
                .addComponent(btnNavInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavReportes)
                .addGap(18, 18, 18)
                .addComponent(btnNavUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEncabezado.setBackground(new java.awt.Color(27, 59, 59));
        pnlEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        lblMarca.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Bigotes & Colas");

        lblSubtituloPantalla.setForeground(new java.awt.Color(207, 227, 223));
        lblSubtituloPantalla.setText("| Inventario");

        lblUsuarioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioSesion.setText("Sesion: Administrador");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMarca)
                .addGap(60, 60, 60)
                .addComponent(lblSubtituloPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(lblUsuarioSesion)
                .addGap(33, 33, 33))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(lblSubtituloPantalla)
                    .addComponent(lblUsuarioSesion))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        txtBuscarProducto.setToolTipText("Buscar producto...");

        btnBuscarProducto.setText("Buscar Producto");

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"M-001", "Amoxicilina 250mg", "42", "03/2027"},
                {"V-014", "Vacuna antirrabica", "6", "11/2026"},
                {"A-203", "Alimento cachorro 2kg", "18", "-"},
                {"M-019", "Desparasitante", "3", "10/2026 "},
                {"", "", null, null}
            },
            new String [] {
                "Codigo", "Producto", "Stock", "Vence"
            }
        ));
        jScrollPane1.setViewportView(tablaInventario);

        lblAlertaStock.setText("⚠ 2 productos bajo stock minimo - 1 vence este mes");

        btnRegistrarEntrada.setBackground(new java.awt.Color(46, 125, 107));
        btnRegistrarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEntrada.setText("Registrar entrada");

        btnRegistrarSalida.setBackground(new java.awt.Color(46, 125, 107));
        btnRegistrarSalida.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarSalida.setText("Registrar salida");

        btnNuevoProducto.setBackground(new java.awt.Color(46, 125, 107));
        btnNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setText("Nuevo producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnBuscarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(147, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlertaStock)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrarEntrada)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegistrarSalida)
                                .addGap(18, 18, 18)
                                .addComponent(btnNuevoProducto)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblAlertaStock)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarEntrada)
                    .addComponent(btnRegistrarSalida)
                    .addComponent(btnNuevoProducto))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(606, 606, 606))
                        .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavMascotasActionPerformed
        // TODO add your handling code here:
        new Mascotas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavMascotasActionPerformed

    private void btnNavHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavHistorialActionPerformed
        // TODO add your handling code here:
        new Historial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavHistorialActionPerformed

    private void btnNavCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavCitasActionPerformed
        // TODO add your handling code here:
        new Citas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavCitasActionPerformed

    private void btnNavInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavInventarioActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnNavInventarioActionPerformed

    private void btnNavUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavUsuariosActionPerformed
        // TODO add your handling code here:
        new Usuarios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inventario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnNavCitas;
    private javax.swing.JButton btnNavClientes;
    private javax.swing.JButton btnNavHistorial;
    private javax.swing.JButton btnNavInventario;
    private javax.swing.JButton btnNavMascotas;
    private javax.swing.JButton btnNavReportes;
    private javax.swing.JButton btnNavUsuarios;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnRegistrarEntrada;
    private javax.swing.JButton btnRegistrarSalida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlertaStock;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblSubtituloPantalla;
    private javax.swing.JLabel lblUsuarioSesion;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
