/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bigotes_colas.views;

import javax.swing.JOptionPane;

/**
 *
 * @author gbcya
 */
public class Mascotas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mascotas.class.getName());

    /**
     * Creates new form Mascotas
     */
    public Mascotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEncabezado = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        lblSubtituloPantalla = new javax.swing.JLabel();
        lblUsuarioSesion = new javax.swing.JLabel();
        pnlSidebar = new javax.swing.JPanel();
        btnNavClientes = new javax.swing.JButton();
        btnNavMascotas = new javax.swing.JButton();
        btnNavHistorial = new javax.swing.JButton();
        btnNavCitas = new javax.swing.JButton();
        btnNavInventario = new javax.swing.JButton();
        btnNavReportes = new javax.swing.JButton();
        btnNavUsuarios = new javax.swing.JButton();
        comboEspecie = new javax.swing.JComboBox<>();
        comboRaza = new javax.swing.JComboBox<>();
        txtBuscarMascota = new javax.swing.JTextField();
        btnBuscarMascota = new javax.swing.JButton();
        txtBuscarRaza = new javax.swing.JTextField();
        btnBuscarRaza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMascotas = new javax.swing.JTable();
        btnAgregarMascota = new javax.swing.JButton();
        btnEditarMascota = new javax.swing.JButton();
        btnEliminarMascota = new javax.swing.JButton();
        btnVerHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEncabezado.setBackground(new java.awt.Color(27, 59, 59));
        pnlEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        lblMarca.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Bigotes & Colas");

        lblSubtituloPantalla.setForeground(new java.awt.Color(207, 227, 223));
        lblSubtituloPantalla.setText(" | Mascotas");

        lblUsuarioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioSesion.setText("Sesion: Administrador");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMarca)
                .addGap(60, 60, 60)
                .addComponent(lblSubtituloPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(lblUsuarioSesion)
                .addGap(33, 33, 33))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(lblSubtituloPantalla)
                    .addComponent(lblUsuarioSesion))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlSidebar.setBackground(new java.awt.Color(233, 243, 241));

        btnNavClientes.setBackground(new java.awt.Color(233, 243, 241));
        btnNavClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavClientes.setForeground(new java.awt.Color(74, 74, 74));
        btnNavClientes.setText("Clientes");

        btnNavMascotas.setBackground(new java.awt.Color(46, 125, 107));
        btnNavMascotas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavMascotas.setForeground(new java.awt.Color(74, 74, 74));
        btnNavMascotas.setText("Mascotas");
        btnNavMascotas.addActionListener(this::btnNavMascotasActionPerformed);

        btnNavHistorial.setBackground(new java.awt.Color(233, 243, 241));
        btnNavHistorial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavHistorial.setForeground(new java.awt.Color(74, 74, 74));
        btnNavHistorial.setText("Historial");
        btnNavHistorial.addActionListener(this::btnNavHistorialActionPerformed);

        btnNavCitas.setBackground(new java.awt.Color(233, 243, 241));
        btnNavCitas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavCitas.setForeground(new java.awt.Color(74, 74, 74));
        btnNavCitas.setText("Citas");
        btnNavCitas.addActionListener(this::btnNavCitasActionPerformed);

        btnNavInventario.setBackground(new java.awt.Color(233, 243, 241));
        btnNavInventario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavInventario.setForeground(new java.awt.Color(74, 74, 74));
        btnNavInventario.setText("Inventario");
        btnNavInventario.addActionListener(this::btnNavInventarioActionPerformed);

        btnNavReportes.setBackground(new java.awt.Color(233, 243, 241));
        btnNavReportes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavReportes.setForeground(new java.awt.Color(74, 74, 74));
        btnNavReportes.setText("Reportes");

        btnNavUsuarios.setBackground(new java.awt.Color(233, 243, 241));
        btnNavUsuarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavUsuarios.setForeground(new java.awt.Color(74, 74, 74));
        btnNavUsuarios.setText("Usuarios");
        btnNavUsuarios.addActionListener(this::btnNavUsuariosActionPerformed);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNavClientes)
                    .addComponent(btnNavMascotas)
                    .addComponent(btnNavHistorial)
                    .addComponent(btnNavCitas)
                    .addComponent(btnNavInventario)
                    .addComponent(btnNavReportes)
                    .addComponent(btnNavUsuarios))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnNavClientes)
                .addGap(18, 18, 18)
                .addComponent(btnNavMascotas)
                .addGap(18, 18, 18)
                .addComponent(btnNavHistorial)
                .addGap(18, 18, 18)
                .addComponent(btnNavCitas)
                .addGap(18, 18, 18)
                .addComponent(btnNavInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavReportes)
                .addGap(18, 18, 18)
                .addComponent(btnNavUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Perro", "Gato" }));

        comboRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Labrador Retriever", "Pastor Alemán", "Golden Retriever", "Chihuahua", "Bulldog", "Poodle", "Beagle", "Husky Siberiano", "Rottweiler", "Dachshund", "Schnauzer", "Pug", "Cocker Spaniel", "Mestizo" }));

        txtBuscarMascota.setToolTipText("Buscar por nombre...");

        btnBuscarMascota.setText("Buscar");

        txtBuscarRaza.setToolTipText("Buscar por nombre...");

        btnBuscarRaza.setText("Buscar");

        tablaMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"M-101", "Firulais", "Perro", " Labrador", "3 anios", "Maria Lopez"},
                {"M-102", "Michi", "Gato", "Siames", "2 anios", "Carlos Ruiz"},
                {"M-103", "Rocky", "Perro", "Pastor Aleman", "5 anios", "Ana Gomez"},
                {"M-104", "Luna", "Gato", "Comun europeo", "1 anio", null}
            },
            new String [] {
                "Codigo", "Nombre", "Especie", "Raza", "Edad", "Dueño"
            }
        ));
        jScrollPane1.setViewportView(tablaMascotas);

        btnAgregarMascota.setText("Agregar mascota");
        btnAgregarMascota.addActionListener(this::btnAgregarMascotaActionPerformed);

        btnEditarMascota.setText("Editar ");
        btnEditarMascota.addActionListener(this::btnEditarMascotaActionPerformed);

        btnEliminarMascota.setText("Eliminar ");
        btnEliminarMascota.addActionListener(this::btnEliminarMascotaActionPerformed);

        btnVerHistorial.setText("Ver historial clinico");
        btnVerHistorial.addActionListener(this::btnVerHistorialActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(comboRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarRaza)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(comboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarMascota))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnAgregarMascota)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarMascota)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarMascota)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerHistorial)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMascota))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRaza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMascota)
                    .addComponent(btnEditarMascota)
                    .addComponent(btnEliminarMascota)
                    .addComponent(btnVerHistorial))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(606, 606, 606))
                        .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavMascotasActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnNavMascotasActionPerformed

    private void btnNavHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavHistorialActionPerformed
        // TODO add your handling code here:
        new Historial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavHistorialActionPerformed

    private void btnNavCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavCitasActionPerformed
        // TODO add your handling code here:
        new Citas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavCitasActionPerformed

    private void btnNavInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavInventarioActionPerformed
        // TODO add your handling code here:
        new Inventario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavInventarioActionPerformed

    private void btnNavUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavUsuariosActionPerformed
        // TODO add your handling code here:
        new Usuarios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNavUsuariosActionPerformed

    private void btnAgregarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMascotaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
    "Accion de prototipo: \"Agregar mascota\"\n(sin logica de negocio todavia)",
    "Prototipo no funcional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAgregarMascotaActionPerformed

    private void btnEditarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMascotaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
    "Accion de prototipo: \"Editar\"\n(sin logica de negocio todavia)",
    "Prototipo no funcional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEditarMascotaActionPerformed

    private void btnEliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMascotaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
    "Accion de prototipo: \"Eliminar\"\n(sin logica de negocio todavia)",
    "Prototipo no funcional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEliminarMascotaActionPerformed

    private void btnVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
    "Accion de prototipo: \"Ver historial clinico\"\n(sin logica de negocio todavia)",
    "Prototipo no funcional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mascotas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMascota;
    private javax.swing.JButton btnBuscarMascota;
    private javax.swing.JButton btnBuscarRaza;
    private javax.swing.JButton btnEditarMascota;
    private javax.swing.JButton btnEliminarMascota;
    private javax.swing.JButton btnNavCitas;
    private javax.swing.JButton btnNavClientes;
    private javax.swing.JButton btnNavHistorial;
    private javax.swing.JButton btnNavInventario;
    private javax.swing.JButton btnNavMascotas;
    private javax.swing.JButton btnNavReportes;
    private javax.swing.JButton btnNavUsuarios;
    private javax.swing.JButton btnVerHistorial;
    private javax.swing.JComboBox<String> comboEspecie;
    private javax.swing.JComboBox<String> comboRaza;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblSubtituloPantalla;
    private javax.swing.JLabel lblUsuarioSesion;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JTable tablaMascotas;
    private javax.swing.JTextField txtBuscarMascota;
    private javax.swing.JTextField txtBuscarRaza;
    // End of variables declaration//GEN-END:variables
}
