/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bigotes_colas.views;

import com.mycompany.bigotes_colas.model.Usuario;
import com.mycompany.bigotes_colas.util.Sesion;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.ListSelectionModel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gbcya
 */
public class Usuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Usuarios.class.getName());

    private final com.mycompany.bigotes_colas.controlador.Usuario controlador =
            new com.mycompany.bigotes_colas.controlador.Usuario();

    private List<Usuario> usuariosCargados = new ArrayList<>();
    private List<Usuario> usuariosVisibles = new ArrayList<>();
    /** Usuario que se está editando; null = el formulario crea uno nuevo. */
    private Usuario usuarioEnEdicion;
    private boolean esAdmin;

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        reorganizarLayout();
        configurarComponentes();
        aplicarPermisos();
        cargarUsuarios();
        pack(); // recalcula el tamaño tras cambiar el texto de la sesión
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        btnNavClientes = new javax.swing.JButton();
        btnNavMascotas = new javax.swing.JButton();
        btnNavHistorial = new javax.swing.JButton();
        btnNavCitas = new javax.swing.JButton();
        btnNavInventario = new javax.swing.JButton();
        btnNavReportes = new javax.swing.JButton();
        btnNavUsuarios = new javax.swing.JButton();
        pnlEncabezado = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        lblSubtituloPantalla = new javax.swing.JLabel();
        lblUsuarioSesion = new javax.swing.JLabel();
        txtBuscarUsuario = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        pnlFormularioUsuario = new javax.swing.JPanel();
        lblNuevoUsuario = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        lblNombreCompleto = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtClaveUsuario = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        comboRolUsuario = new javax.swing.JComboBox<>();
        btnGuardarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnResetClave = new javax.swing.JButton();
        btnSuspenderUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSidebar.setBackground(new java.awt.Color(233, 243, 241));

        btnNavClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavClientes.setForeground(new java.awt.Color(74, 74, 74));
        btnNavClientes.setText("Clientes");
        btnNavClientes.addActionListener(this::btnNavClientesActionPerformed);

        btnNavMascotas.setBackground(new java.awt.Color(233, 243, 241));
        btnNavMascotas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavMascotas.setForeground(new java.awt.Color(74, 74, 74));
        btnNavMascotas.setText("Mascotas");
        btnNavMascotas.addActionListener(this::btnNavMascotasActionPerformed);

        btnNavHistorial.setBackground(new java.awt.Color(233, 243, 241));
        btnNavHistorial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavHistorial.setForeground(new java.awt.Color(74, 74, 74));
        btnNavHistorial.setText("Historial");
        btnNavHistorial.addActionListener(this::btnNavHistorialActionPerformed);

        btnNavCitas.setBackground(new java.awt.Color(233, 243, 241));
        btnNavCitas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavCitas.setForeground(new java.awt.Color(74, 74, 74));
        btnNavCitas.setText("Citas");
        btnNavCitas.addActionListener(this::btnNavCitasActionPerformed);

        btnNavInventario.setBackground(new java.awt.Color(233, 243, 241));
        btnNavInventario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavInventario.setForeground(new java.awt.Color(74, 74, 74));
        btnNavInventario.setText("Inventario");
        btnNavInventario.addActionListener(this::btnNavInventarioActionPerformed);

        btnNavReportes.setBackground(new java.awt.Color(233, 243, 241));
        btnNavReportes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNavReportes.setForeground(new java.awt.Color(74, 74, 74));
        btnNavReportes.setText("Reportes");
        btnNavReportes.addActionListener(this::btnNavReportesActionPerformed);

        btnNavUsuarios.setBackground(new java.awt.Color(46, 125, 107));
        btnNavUsuarios.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnNavUsuarios.setText("Usuarios");
        btnNavUsuarios.addActionListener(this::btnNavUsuariosActionPerformed);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNavClientes)
                    .addComponent(btnNavMascotas)
                    .addComponent(btnNavHistorial)
                    .addComponent(btnNavCitas)
                    .addComponent(btnNavInventario)
                    .addComponent(btnNavReportes)
                    .addComponent(btnNavUsuarios))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnNavClientes)
                .addGap(18, 18, 18)
                .addComponent(btnNavMascotas)
                .addGap(18, 18, 18)
                .addComponent(btnNavHistorial)
                .addGap(18, 18, 18)
                .addComponent(btnNavCitas)
                .addGap(18, 18, 18)
                .addComponent(btnNavInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavReportes)
                .addGap(18, 18, 18)
                .addComponent(btnNavUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEncabezado.setBackground(new java.awt.Color(27, 59, 59));
        pnlEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        lblMarca.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Bigotes & Colas");

        lblSubtituloPantalla.setForeground(new java.awt.Color(207, 227, 223));
        lblSubtituloPantalla.setText("| Usuarios");

        lblUsuarioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioSesion.setText("Sesion: Administrador");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMarca)
                .addGap(60, 60, 60)
                .addComponent(lblSubtituloPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(lblUsuarioSesion)
                .addGap(33, 33, 33))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(lblSubtituloPantalla)
                    .addComponent(lblUsuarioSesion))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        txtBuscarUsuario.setToolTipText("Buscar usuario...");

        btnBuscarUsuario.setText("Buscar");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"admin", "Ana Lopez", "Administrador", "Activo"},
                {"jmendez", "Dr. Mendez", "Veterinario", "Activo"},
                {"msolis", "Dra. Solis", "Veterinario", "Activo"},
                {"recepcion1", "Luisa Ramirez", "Recepcionista", "Activo"}
            },
            new String [] {
                "Usuario", "Nombre Completo", "Rol", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        pnlFormularioUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 243, 241), 2));

        lblNuevoUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNuevoUsuario.setText("Nuevo usuario");

        lblNombreCompleto.setText("Nombre Completo:");

        lblUsuario.setText("Usuario:");

        jLabel1.setText("Contraseña:");

        jLabel2.setText("Rol:");

        comboRolUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Veterinario", "Recepcionista" }));

        btnGuardarUsuario.setText("Guardar usuario");

        javax.swing.GroupLayout pnlFormularioUsuarioLayout = new javax.swing.GroupLayout(pnlFormularioUsuario);
        pnlFormularioUsuario.setLayout(pnlFormularioUsuarioLayout);
        pnlFormularioUsuarioLayout.setHorizontalGroup(
            pnlFormularioUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioUsuarioLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lblNombreCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlFormularioUsuarioLayout.createSequentialGroup()
                .addGroup(pnlFormularioUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioUsuarioLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblNuevoUsuario))
                    .addGroup(pnlFormularioUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFormularioUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioUsuarioLayout.createSequentialGroup()
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreUsuario))
                    .addGroup(pnlFormularioUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtClaveUsuario))
                    .addGroup(pnlFormularioUsuarioLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnGuardarUsuario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlFormularioUsuarioLayout.setVerticalGroup(
            pnlFormularioUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNuevoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarUsuario)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnEditarUsuario.setText("Editar ");

        btnEliminarUsuario.setText("Eliminar ");

        btnResetClave.setText("Restablecer contrasena");

        btnSuspenderUsuario.setText("Suspender Usuario");
        btnSuspenderUsuario.addActionListener(this::btnSuspenderUsuarioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlFormularioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscarUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnEditarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetClave)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuspenderUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(647, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarUsuario))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFormularioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarUsuario)
                    .addComponent(btnEliminarUsuario)
                    .addComponent(btnResetClave)
                    .addComponent(btnSuspenderUsuario))
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>                        

    private void btnNavMascotasActionPerformed(java.awt.event.ActionEvent evt) {                                               
        new Mascotas().setVisible(true);
        this.dispose();
    }                                              

    private void btnNavHistorialActionPerformed(java.awt.event.ActionEvent evt) {                                                
        new Historial().setVisible(true);
        this.dispose();
    }                                               

    private void btnNavCitasActionPerformed(java.awt.event.ActionEvent evt) {                                            
        new Citas().setVisible(true);
        this.dispose();
    }                                           

    private void btnNavInventarioActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        new Inventario().setVisible(true);
        this.dispose();
    }                                                

    private void btnNavUsuariosActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Ya estamos en Usuarios
    }                                              

    private void btnSuspenderUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        suspenderOReactivar();
    }                                                   

    private void btnNavClientesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        new Clientes().setVisible(true);
        this.dispose();
    }                                              

    private void btnNavReportesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        new Reportes().setVisible(true);
        this.dispose();
    }                                              

    // =====================================================================
    //  Código propio (fuera de initComponents para que NetBeans no lo borre)
    // =====================================================================

    /**
     * Reacomoda los componentes del diseñador con layouts que se adaptan al
     * tamaño: el encabezado queda alineado a la derecha del menú lateral y ya
     * no se encima aunque el texto de la sesión sea largo.
     * (El diseñador de NetBeans seguirá mostrando la distribución original.)
     */
    private void reorganizarLayout() {
        Container contenido = getContentPane();
        contenido.removeAll();
        contenido.setLayout(new BorderLayout(20, 0));
        ((JComponent) contenido).setBorder(new EmptyBorder(10, 10, 10, 10));

        // Barra de búsqueda
        txtBuscarUsuario.setColumns(18);
        JPanel busqueda = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 0));
        busqueda.add(btnBuscarUsuario);
        busqueda.add(txtBuscarUsuario);

        // Tabla a la izquierda, formulario a la derecha
        jScrollPane1.setPreferredSize(new Dimension(430, 230));
        JPanel medio = new JPanel(new BorderLayout(18, 0));
        medio.add(jScrollPane1, BorderLayout.CENTER);
        medio.add(pnlFormularioUsuario, BorderLayout.EAST);

        JPanel cuerpo = new JPanel(new BorderLayout(0, 14));
        cuerpo.add(busqueda, BorderLayout.NORTH);
        cuerpo.add(medio, BorderLayout.CENTER);

        // Botones de acción
        JPanel acciones = new JPanel(new FlowLayout(FlowLayout.CENTER, 18, 0));
        acciones.add(btnEditarUsuario);
        acciones.add(btnEliminarUsuario);
        acciones.add(btnResetClave);
        acciones.add(btnSuspenderUsuario);

        // Columna derecha: encabezado arriba, cuerpo al centro, botones abajo
        JPanel centro = new JPanel(new BorderLayout(0, 18));
        centro.setBorder(new EmptyBorder(20, 0, 10, 10));
        centro.add(pnlEncabezado, BorderLayout.NORTH);
        centro.add(cuerpo, BorderLayout.CENTER);
        centro.add(acciones, BorderLayout.SOUTH);

        contenido.add(pnlSidebar, BorderLayout.WEST);
        contenido.add(centro, BorderLayout.CENTER);
        setMinimumSize(new Dimension(900, 560));
    }

    private void configurarComponentes() {
        // Tabla de solo lectura, sin los datos de ejemplo
        tablaUsuarios.setModel(new DefaultTableModel(
                new String[] { "Usuario", "Nombre completo", "Rol", "Estado" }, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        });
        tablaUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaUsuarios.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) actualizarBotonSuspender();
        });

        // Acciones de los botones (Suspender ya viene conectado desde initComponents)
        btnBuscarUsuario.addActionListener(e -> aplicarFiltro());
        txtBuscarUsuario.addActionListener(e -> aplicarFiltro()); // Enter
        btnGuardarUsuario.addActionListener(e -> guardarUsuario());
        btnEditarUsuario.addActionListener(e -> editarOCancelar());
        btnEliminarUsuario.addActionListener(e -> eliminarUsuario());
        btnResetClave.addActionListener(e -> restablecerClave());

        // Textos
        btnEditarUsuario.setText("Editar");
        btnEliminarUsuario.setText("Eliminar");
        btnResetClave.setText("Restablecer contraseña");
        btnSuspenderUsuario.setText("Suspender usuario");
        txtBuscarUsuario.setToolTipText("Usuario, nombre o rol...");
    }

    private void aplicarPermisos() {
        Usuario actual = Sesion.getUsuarioActual();
        if (actual != null) {
            lblUsuarioSesion.setText("Sesión: " + actual.getNombre() + " (" + actual.getRol() + ")");
        }
        esAdmin = actual != null && actual.esAdministrador();

        List<JComponent> controles = Arrays.asList(
                txtNombreCompleto, txtNombreUsuario, txtClaveUsuario, comboRolUsuario,
                btnGuardarUsuario, btnEditarUsuario, btnEliminarUsuario,
                btnResetClave, btnSuspenderUsuario);
        for (JComponent c : controles) {
            c.setEnabled(esAdmin);
        }
        if (!esAdmin) {
            lblNuevoUsuario.setText("Solo lectura");
            lblNuevoUsuario.setToolTipText("La gestión de usuarios requiere rol Administrador");
        }
    }

    private void cargarUsuarios() {
        try {
            usuariosCargados = controlador.listar();
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar usuarios", ex);
            usuariosCargados = new ArrayList<>();
            JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        aplicarFiltro();
    }

    private void aplicarFiltro() {
        String texto = txtBuscarUsuario.getText().trim().toLowerCase(Locale.ROOT);
        usuariosVisibles = texto.isEmpty()
                ? usuariosCargados
                : usuariosCargados.stream()
                        .filter(u -> contiene(u.getUsuario(), texto)
                                || contiene(u.getNombre(), texto)
                                || contiene(u.getRol(), texto))
                        .toList();

        DefaultTableModel modelo = (DefaultTableModel) tablaUsuarios.getModel();
        modelo.setRowCount(0);
        for (Usuario u : usuariosVisibles) {
            modelo.addRow(new Object[] {
                u.getUsuario(), u.getNombre(), u.getRol(), u.isActivo() ? "Activo" : "Suspendido"
            });
        }
        actualizarBotonSuspender();
    }

    // ===================== Acciones =====================

    private void guardarUsuario() {
        String nombre = txtNombreCompleto.getText().trim();
        String usuario = txtNombreUsuario.getText().trim();
        String rol = (String) comboRolUsuario.getSelectedItem();
        char[] claveChars = txtClaveUsuario.getPassword();

        try {
            if (usuarioEnEdicion == null) {
                controlador.crear(nombre, usuario, new String(claveChars), rol);
                JOptionPane.showMessageDialog(this, "Usuario \"" + usuario + "\" creado.");
            } else {
                controlador.actualizar(usuarioEnEdicion.getIdUsuario(), nombre, usuario, rol);
                JOptionPane.showMessageDialog(this, "Usuario \"" + usuario + "\" actualizado.");
            }
            limpiarFormulario();
            cargarUsuarios();
        } catch (IllegalArgumentException | IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Revisa los datos", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            Arrays.fill(claveChars, '\0'); // no dejar la contraseña en memoria
        }
    }

    /** Carga el usuario seleccionado en el formulario, o cancela la edición en curso. */
    private void editarOCancelar() {
        if (usuarioEnEdicion != null) {
            limpiarFormulario();
            return;
        }
        Usuario u = obtenerSeleccionado(true);
        if (u == null) return;

        usuarioEnEdicion = u;
        txtNombreCompleto.setText(u.getNombre());
        txtNombreUsuario.setText(u.getUsuario());
        comboRolUsuario.setSelectedItem(u.getRol());
        txtClaveUsuario.setText("");
        txtClaveUsuario.setEnabled(false);
        txtClaveUsuario.setToolTipText("Para cambiarla usa \"Restablecer contraseña\"");

        lblNuevoUsuario.setText("Editar usuario");
        btnGuardarUsuario.setText("Guardar cambios");
        btnEditarUsuario.setText("Cancelar edición");
        txtNombreCompleto.requestFocus();
    }

    private void eliminarUsuario() {
        Usuario u = obtenerSeleccionado(true);
        if (u == null) return;

        int confirmar = JOptionPane.showConfirmDialog(this,
                "¿Eliminar al usuario \"" + u.getUsuario() + "\" (" + u.getNombre() + ")?\n"
                + "Esta acción no se puede deshacer.",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirmar != JOptionPane.YES_OPTION) return;

        try {
            controlador.eliminar(u.getIdUsuario(), idUsuarioSesion());
            if (usuarioEnEdicion != null && usuarioEnEdicion.getIdUsuario() == u.getIdUsuario()) {
                limpiarFormulario();
            }
            cargarUsuarios();
        } catch (IllegalArgumentException | IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "No se puede eliminar", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void restablecerClave() {
        Usuario u = obtenerSeleccionado(true);
        if (u == null) return;

        JPasswordField txtNueva = new JPasswordField(15);
        JPasswordField txtConfirmar = new JPasswordField(15);
        JPanel panel = new JPanel(new GridLayout(0, 1, 0, 4));
        panel.add(new JLabel("Nueva contraseña para \"" + u.getUsuario() + "\":"));
        panel.add(txtNueva);
        panel.add(new JLabel("Confirmar contraseña:"));
        panel.add(txtConfirmar);

        while (true) {
            int r = JOptionPane.showConfirmDialog(this, panel, "Restablecer contraseña",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (r != JOptionPane.OK_OPTION) return;

            char[] nueva = txtNueva.getPassword();
            char[] confirmar = txtConfirmar.getPassword();
            try {
                if (!Arrays.equals(nueva, confirmar)) {
                    JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
                    continue;
                }
                controlador.restablecerClave(u.getIdUsuario(), new String(nueva));
                JOptionPane.showMessageDialog(this, "Contraseña de \"" + u.getUsuario() + "\" actualizada.");
                return;
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage()); // muy corta: vuelve a pedir
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } finally {
                Arrays.fill(nueva, '\0');
                Arrays.fill(confirmar, '\0');
            }
        }
    }

    private void suspenderOReactivar() {
        Usuario u = obtenerSeleccionado(true);
        if (u == null) return;

        boolean suspender = u.isActivo();
        String mensaje = suspender
                ? "¿Suspender a \"" + u.getUsuario() + "\"?\nNo podrá iniciar sesión hasta que lo reactives."
                : "¿Reactivar a \"" + u.getUsuario() + "\"?";
        int confirmar = JOptionPane.showConfirmDialog(this, mensaje,
                suspender ? "Suspender usuario" : "Reactivar usuario", JOptionPane.YES_NO_OPTION);
        if (confirmar != JOptionPane.YES_OPTION) return;

        try {
            controlador.cambiarEstado(u.getIdUsuario(), !suspender, idUsuarioSesion());
            cargarUsuarios();
        } catch (IllegalArgumentException | IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "No permitido", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // ===================== Utilidades =====================

    private void limpiarFormulario() {
        usuarioEnEdicion = null;
        txtNombreCompleto.setText("");
        txtNombreUsuario.setText("");
        txtClaveUsuario.setText("");
        txtClaveUsuario.setEnabled(esAdmin);
        txtClaveUsuario.setToolTipText(null);
        comboRolUsuario.setSelectedIndex(0);
        lblNuevoUsuario.setText(esAdmin ? "Nuevo usuario" : "Solo lectura");
        btnGuardarUsuario.setText("Guardar usuario");
        btnEditarUsuario.setText("Editar");
    }

    /** Cambia el texto del botón a "Suspender" o "Reactivar" según el usuario seleccionado. */
    private void actualizarBotonSuspender() {
        Usuario u = obtenerSeleccionado(false);
        btnSuspenderUsuario.setText(u != null && !u.isActivo() ? "Reactivar usuario" : "Suspender usuario");
    }

    private Usuario obtenerSeleccionado(boolean avisar) {
        int filaVista = tablaUsuarios.getSelectedRow();
        if (filaVista == -1) {
            if (avisar) JOptionPane.showMessageDialog(this, "Selecciona un usuario de la tabla primero.");
            return null;
        }
        int fila = tablaUsuarios.convertRowIndexToModel(filaVista);
        return (fila < usuariosVisibles.size()) ? usuariosVisibles.get(fila) : null;
    }

    private int idUsuarioSesion() {
        Usuario actual = Sesion.getUsuarioActual();
        return actual != null ? actual.getIdUsuario() : -1;
    }

    private static boolean contiene(String valor, String texto) {
        return valor != null && valor.toLowerCase(Locale.ROOT).contains(texto);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Usuarios().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JButton btnNavCitas;
    private javax.swing.JButton btnNavClientes;
    private javax.swing.JButton btnNavHistorial;
    private javax.swing.JButton btnNavInventario;
    private javax.swing.JButton btnNavMascotas;
    private javax.swing.JButton btnNavReportes;
    private javax.swing.JButton btnNavUsuarios;
    private javax.swing.JButton btnResetClave;
    private javax.swing.JButton btnSuspenderUsuario;
    private javax.swing.JComboBox<String> comboRolUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblNuevoUsuario;
    private javax.swing.JLabel lblSubtituloPantalla;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioSesion;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlFormularioUsuario;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtBuscarUsuario;
    private javax.swing.JPasswordField txtClaveUsuario;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration                   
}